version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/openjdk:8.0
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Build Module
          command: ./gradlew assemble
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - run:
          name: Publish Image
          command: ./gradlew publish

workflows:
  build-and-publish:
    jobs:
      - publish:
          name: Build and Publish
          context:
            - maven-creds
